import { Server } from '@colyseus/core';
import { WebSocketTransport } from '@colyseus/ws-transport';
import express from 'express';
import path from 'node:path';
import RAPIER from '@dimforge/rapier3d-compat';
import { flushResults } from './results';
import { ArenaRoom } from './arena-room';
await RAPIER.init();
const transport=new WebSocketTransport({maxPayload:2048,pingInterval:5000,pingMaxRetries:3});
const server=new Server({transport,greet:false});
const app=transport.getExpressApp();
app.disable('x-powered-by');
app.use((_req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');next();});
app.get('/health',(_req,res)=>res.json({ok:true,game:'crossfire-circuit',version:'barrel-balance-3',rooms:ArenaRoom.active.size,players:[...ArenaRoom.active].reduce((n,r)=>n+r.players.size,0)}));
app.use(express.static(path.resolve('dist'),{index:'index.html',maxAge:'1h',setHeaders:(res,file)=>{if(file.endsWith('.html'))res.setHeader('Cache-Control','no-cache');}}));
server.define('circuit',ArenaRoom);
await server.listen(Number(process.env.PORT??2567),process.env.HOST??'127.0.0.1');
setInterval(()=>void flushResults(),15000).unref();void flushResults();
console.log('Crossfire Colyseus listening');
